---
version: '1.0'
services:
  app:
    image: app:latest
    volumes:
      - ./config:/app/config
    container_name: app
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
