---
- name: Configure servers and install Docker
  hosts: all
  become: true
  vars_files: ansible_creds.yml
  roles:
    - common

- name: Configure working directory for database container
  hosts: database
  roles:
    - database

