version: '1.0'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./backup/${database}02.sql:/docker-entrypoint-initdb.d/${database}02.sql
    environment:
      MARIADB_DATABASE: ${database}
      MYSQL_ROOT_PASSWORD: ${root_pass}
      MYSQL_USER: ${user}
      MYSQL_PASSWORD: ${password}
    env_file:
      - .env
